const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..');
const indexPath = path.join(rootDir, 'index.html');
const shopPath = path.join(rootDir, 'shop.html');

const content = fs.readFileSync(indexPath, 'utf-8');

const mainStart = content.indexOf('<main>');
const mainEnd = content.indexOf('</main>') + '</main>'.length;

const beforeMain = content.substring(0, mainStart);
const afterMain = content.substring(mainEnd);

const newMain = `
  <main>
    <div class="product-container" style="margin-top: 30px; margin-bottom: 30px;">
      <div class="container">
        <!-- Sidebar Filters -->
        <div class="sidebar has-scrollbar" data-mobile-menu>
          <div class="sidebar-category">
            <div class="sidebar-top">
              <h2 class="sidebar-title" style="font-size: 1.5rem; font-weight: bold; margin-bottom: 10px;">Filters</h2>
            </div>
            
            <div id="shop-filters" style="margin-top:20px;">
                <h3 style="margin-bottom: 15px; font-weight: bold; font-size: 1.2rem; color: var(--onyx);">Categories</h3>
                <div id="category-filters" style="display:flex; flex-direction:column; gap:12px; font-size: 1rem; color: var(--sonic-silver);">
                  <!-- Checkboxes generated by JS -->
                  <p>Loading filters...</p>
                </div>
                
                <h3 style="margin-top: 30px; margin-bottom: 15px; font-weight: bold; font-size: 1.2rem; color: var(--onyx);">Max Price</h3>
                <div style="display:flex; align-items:center; gap:10px;">
                  <input type="range" id="price-slider" min="0" max="200" value="200" style="width: 100%;">
                  <span id="price-display" style="font-weight:bold; color:var(--onyx);">$200</span>
                </div>
            </div>
          </div>
        </div>

        <div class="product-box">
          <div class="product-main">
            <h2 class="title" id="shop-title">All Products</h2>
            <div class="product-grid" id="shop-product-grid">
               <!-- Products injected via shop.js -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
`;

let finalContent = beforeMain + newMain + afterMain;

// Change title
finalContent = finalContent.replace('<title>Anon - eCommerce Website</title>', '<title>Shop - Devangi Sewing Store</title>');
finalContent = finalContent.replace('<title>Devangi Sewing Store - eCommerce Website</title>', '<title>Shop - Devangi Sewing Store</title>');

// Replace dynamic-products.js with shop.js
finalContent = finalContent.replace('<script src="./assets/js/dynamic-products.js"></script>', '<script src="./assets/js/shop.js"></script>');

fs.writeFileSync(shopPath, finalContent);
console.log('shop.html successfully regenerated');
